# Matrix and Matrix Symbol
 
선형대수학을 공부하는데 적어도 행렬과 행렬기호 정도는 숙지를 하고 진행하는게 낫겠다싶어 작성해보았다.  
- 순서는 연관성을 고려하지않고 알파벳순으로 나열했다.
- 이 행렬이 어떤 경우에 쓰이는지를 나타내기보단 개념전달에 의의를 두었다.

### 임의의 행렬(A)

### 순환행렬(C): circulant matrix

퇴플리츠행렬의 일종으로 각 행 벡터는 선행 행 벡터에 비례하여 오른쪽으로 한 요소(성분)만큼 회전한다.
- 퇴플리츠행렬(Toeplitz matrix): 대각선 위의 성분들이 같은 정사각행렬을 말한다.

간단하게 예시로 행렬을 나타내보자면 다음과 같이 나타낼 수 있다.  
$\begin{bmatrix}a_0&a_1&a_2&a_3&a_4\\a_4&a_0&a_1&a_2&a_3\\a_3&a_4&a_0&a_1&a_2\\a_2&a_3&a_4&a_0&a_1\\a_1&a_2&a_3&a_4&a_0\\ \end{bmatrix}$  
-열행렬을 나타낼때도 같은 기호가 쓰인다.

### 대각행렬(D): diagonal matrix

주 대각선이 아닌 성분들이 전부 0을 갖는 정사각행렬을 말한다.

### 단위행렬(I):  identity matrix
대각행렬인데 대각선을 이루는 원소가 전부 1인 행렬이다.  
**단위행렬은 행렬의 곱셈에 대한 항등원이다.**

자기자신에 어떠한 값을 곱해도 자기 자신이 나오는 성질을 말하는데 직접 풀어써보면 바로 이해할 수 있지만 코드로 나타내보았다.

In [1]:
import numpy as np

A=np.array([[1,2],[3,4]])
I=np.array([[1,0],[0,1]])

print(A@I)

[[1 2]
 [3 4]]


### 하삼각행렬(L): lower triangular matrix  

주대각선을 기준으로 위쪽에 위치한 원소들이 전부 0인값을 말한다.  

In [2]:
#원소는 의미없이 대입했다.
L=np.array([[1,0,0,0],[3,4,0,0],[4,3,1,0],[4,3,2,4]])

print(L)

[[1 0 0 0]
 [3 4 0 0]
 [4 3 1 0]
 [4 3 2 4]]


### 마르코프행렬(M): markov matrix
마르코프행렬은 마르코프 연쇄에서 확률 과정으로 표현된다.
무슨 말인가 싶다..한번 알아보자. 
<br/>
마르코프 연쇄(Markov chain): 어떤 사건 발생할 확률값이 시간에 따라 변해가는 과정
<bf/>
이때 특정 조건을 만족해야하는데 그것은 아래의 내용과 같다.  
- 시간이 이산적으로 변한다.
- 특정시간에 사건이 발생할 확률은 그 이전 시간에 발생한 사건에 대해서만 영향을 받는다.

마르코프행렬은 아래와 같은 특징이 있다.
- 모든 요소가 0보다 크거나 같다. 즉,양수이다.
- 각 열 벡터들의 요소들을 더하면 1이 되는 행렬이다.

### 투영행렬(P): projection matrix  
대칭행렬에 속하며 정사영 행렬이라고도 불린다.  
아래와 같은 특징들을 가진다.  
${P^2=P}$  
${P^T=P}$  
${P^TP=P}$

### 직교행렬(Q): orthogonal matrix  
행렬의 열과 행벡터들이 자기 자신을 제외한 모든 열,행벡터들과 직교이면서 동시에 단위행렬인 것을 의미한다

와닿지 않을 수 있어 작성해보면 다음과 같다.  
$Q=\begin{bmatrix}0&0&1\\1&0&0\\0&1&0\\ \end{bmatrix}$  

직교행렬Q와 Q의 전치행렬을 곱하면 단위행렬(I)가 나온다.

In [3]:
Q=np.array([[0,0,1],[1,0,0],[0,1,0]])
print(Q@Q.T)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 상삼각행렬(R,U): upper triangular matrix  
주대각선을 기준으로 아래쪽 원소들이 전부 0인 행렬을 말한다.  
- 주로 행렬기호 U로 표현한다.

### 대칭행렬(S): symmetric matrix  
전치행렬이 자기 자신과 같은 값이다.  
$A=A^T$

### 텐서(T): Tensor
미분기하학과 대수학에 따라 차이점이 있지만 머신러닝을 다루는데 있어서는 다차원배열 정도로 이해하고 있으면 될 듯하다.

### 고유벡터행렬(X): eigenvalue vector matrix
고유벡터행렬과 고유값행렬이 정확히 무슨 차이가 있는지는 모르겠다.
<br/>
### 고유값행렬(거꾸로된 V형태를 띄고있다. ): eigenvalue matrix
↑찾아봐도 마크다운 표현방법을 모르겠다..

고유벡터와 함께 임의의 대상이되는 행렬의 특성을 보여주는 정보를 갖고있는 행렬을 말한다.
- 고유벡터: 선형변환 A에 의한 변환 결과가 자기 자신의 상수배가 되는 0이 아닌 벡터를 말한다.

Av = λv를 만족한다고 한다면 v는 고유벡터, λ를 고유값이라고 칭한다.

이 밖에도 푸리에행렬(F), 혼합행렬(M), 표본 공분산행렬(S), 좌특이벡터(U), 우특이벡터(V), 특이값행렬($\displaystyle\sum_{}^{}{}$)등이 존재하지만 공부를 더 해봐야할 것같다...